---

- name: "ara Install and setup"
  hosts: localhost
  connection: local
  vars:
    ara_docker_image: "docker.io/recordsansible/ara-api"
  tasks:
    - name: create ara required folders
      file:
        state: directory
        path: "{{ item }}"
      with_items:
        - "/opt/ara"

    - name: Deploy ara
      docker_container:
        name: "ara"
        hostname: "ara"
        image: "{{ ara_docker_image }}"
        env:
          TZ: 'America/Toronto'
        labels:
          traefik.enable: "true"
          traefik.docker.network: "app_network"
          traefik.http.routers.ara.rule: "Host(`ara.{{ do_domain }}`)"
          traefik.http.routers.ara.entrypoints: "https"
          traefik.http.routers.ara.tls: "true"
          traefik.http.routers.ara.tls.certresolver: "le"
          traefik.http.services.ara.loadbalancer.server.port: "8000"
        networks:
          - name: "app_network"
        volumes:
          - '/opt/ara:/opt/ara'
        restart_policy: always
        state: started
        pull: false
        network_mode: "default"
        container_default_behavior: "no_defaults"
      # added retry to tasks dependant on external services
      register: result
      retries: 5
      delay: 3
      until: result is succeeded
      when: not ansible_check_mode
