---

- hosts: all
  tasks:
    - name: Install apt-file
      package:
        name: "apt-file"

    - name: Install packages by binaries
      shell: apt-get -y install $(apt-file search --regexp '{{ with_items }}' | head -n 1 | cut -d ':' -f1)
      with_items:
        - '/bin/netstat$'
        - '/bin/ping$'
        - '/bin/curl$'
        - '/bin/vim$'
        - '/bin/wget$'
