---

- name: "Ensuring laptop stays awake"
  hosts: localhost
  connection: local
  handlers:
    - name: Update Grub
      command: update-grub
  tasks:
    - name: "Disable any kind of sleep"
      systemd:
        name: "{{ item }}"
        enabled: false
        masked: true
      with_items:
        - sleep.target
        - suspend.target
        - hibernate.target
        - hybrid-sleep.target
