---

- name: "Disabling unattended upgrades"
  hosts: localhost
  connection: local
  tasks:
    - name: "Gather service facts"
      service_facts:

    - name: "Disable unattended upgrades service"
      systemd:
        name: "unattended-upgrades.service"
        enabled: false
        masked: true
      when: ansible_facts.services["unattended-upgrades.service"] is defined
