---

- name: "Ensuring laptop stays awake"
  hosts: localhost
  connection: local
  tasks:
    - name: "Disable any kind of sleep"
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: false
        masked: true
      loop:
        - sleep.target
        - suspend.target
        - hibernate.target
        - hybrid-sleep.target
