---

- name: "Managing DNS config on the host"
  hosts: localhost
  connection: local
  vars:
    resolv_role_version: 1.3.2
    upstream_nameservers:
      - "8.8.8.8"
      - "8.8.4.4"
  tasks:
    - name: create role folder
      file:
        state: directory
        path: /root/.ansible/roles

    - name: Clone role ahuffman.resolv
      git:
        repo: 'https://github.com/ahuffman/ansible-resolv.git'
        dest: /root/.ansible/roles/ahuffman.resolv
        version: "{{ resolv_role_version }}"
      # added retry to tasks dependant on external services
      register: result
      retries: 5
      delay: 3
      until: result is succeeded

    - name: Using unbound role
      include_role:
        name: ahuffman.resolv
      vars:
        resolv_nameservers: "{{ upstream_nameservers }}"
        resolv_options:
          - "timeout:2"
          - "rotate"
      when: not ansible_check_mode

    - name: "Disable systemd-resolv"
      systemd:
        name: "systemd-resolved"
        enabled: false
        masked: true
        state: "stopped"
