---

- name: "Docker installation and setup"
  hosts: localhost
  connection: local
  vars:
    nvidia_docker_version: "2.9.1-1"
  handlers:
    - name: Restart docker
      systemd:
        name: "docker"
        state: restarted
      # Skipping check mode since its causes issues :(
      when: not ansible_check_mode
  tasks:
    - name: Gather package facts
      package_facts:

    - name: create role folder
      file:
        state: directory
        path: /root/.ansible/roles

    - name: Clone role gbolo.docker
      git:
        repo: 'https://github.com/gbolo/ansible-role-docker.git'
        dest: /root/.ansible/roles/gbolo.docker
        version: v2.1

    - name: Using docker role
      include_role:
        name: gbolo.docker
      vars:
        docker_config_log_opts: {
          "max-size": "100m",
          "max-file": "5"
        }
        docker_install_py_module: true
        docker_py_pkg_name: "python3-docker"
      when: not ansible_check_mode

    - name: Add an Apt signing key for Nvidia Docker
      apt_key:
        url: https://nvidia.github.io/nvidia-docker/gpgkey
        state: present

    - name: Add Nvidia Docker repository
      get_url:
        url: https://nvidia.github.io/nvidia-docker/{{ ansible_facts['distribution'] | lower() }}{{ ansible_facts['distribution_version'] }}/nvidia-docker.list
        dest: /etc/apt/sources.list.d/nvidia-docker.list

    - name: Install Nvidia Docker package
      apt:
        name: "nvidia-docker2={{ nvidia_docker_version }}"
        update_cache: true
      # https://github.com/ansible/ansible/issues/45219
      environment:
        PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      when:
        - (not 'nvidia-docker2' in ansible_facts.packages) or ('nvidia-docker2' in ansible_facts.packages and ansible_facts.packages['nvidia-docker2'][0].version != nvidia_docker_version)
        - not ansible_check_mode
      notify:
        - Restart docker
