---

- hosts: all
  tasks:
    - name: create role folder
      file:
        state: directory
        path: /root/.ansible/roles

    - name: Clone role gbolo.docker
      git:
        repo: 'https://github.com/gbolo/ansible-role-docker.git'
        dest: /root/.ansible/roles/gbolo.docker
        version: v2.1

    - name: Using unbound role
      include_role:
        name: gbolo.unbound
      vars:
        docker_config_log_opts: {
          "max-size": "100m",
          "max-file": "5"
        }
