---

- hosts: all
  tasks:
  vars:
    emby_version: "4.6.4.0"
    emby_download_url: "https://github.com/MediaBrowser/Emby.Releases/releases/download/{{ emby_version }}/emby-server-deb_{{ emby_version }}_amd64.deb"
  tasks:
    - name: Install Emby
      apt:
        deb: "{{ emby_download_url }}"

    - name: Ensure Emby server is enabled
      systemd:
        name: "emby-server"
        enable: true
        state: started
