---

- name: "Install and Setup Emby"
  hosts: localhost
  connection: local
  vars:
    emby_version: "4.6.3.0"
    emby_download_url: "https://github.com/MediaBrowser/Emby.Releases/releases/download/{{ emby_version }}/emby-server-deb_{{ emby_version }}_amd64.deb"
    emby_root: "/var/lib/emby"

  handlers:
    - name: Restart Emby
      systemd:
        name: "emby-server"
        state: restarted
      # Skipping check mode since its causes issues :(
      when: not ansible_check_mode

  tasks:
    - name: Install Emby
      apt:
        deb: "{{ emby_download_url }}"
      # https://github.com/ansible/ansible/issues/45219
      environment:
        PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

    - name: Ensure Emby server is enabled
      systemd:
        name: "emby-server"
        enabled: true
        state: started
      # Skipping check mode since its causes issues :(
      when: not ansible_check_mode

    - name: Create folders for content
      file:
        state: directory
        path: "{{ item }}"
        owner: "emby"
        group: "emby"
      with_items:
        - "{{ emby_root }}/config"
        - "{{ emby_root }}/root/default/TV shows"
        - "{{ emby_root }}/root/default/Movies"

    - name: Get cksum of system.xml in git
      stat:
        path: "../files/emby/system.xml"
      register: gitsystemxml

    - name: Get cksum of my system.xml deployed
      stat:
        path: "{{ emby_root }}/config/system.xml"
      register: embysystemxml

    - name: Config changed
      debug:
        msg: "File Compare"
      failed_when:  gitsystemxml.stat.checksum != embysystemxml.stat.checksum

    - name: Copy config files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "emby"
        group: "emby"
      with_items:
        - src: "../files/emby/system.xml"
          dest: "{{ emby_root }}/config/system.xml"
        - src: "../files/emby/TV_shows_options.xml"
          dest: "{{ emby_root }}/root/default/TV shows/options.xml"
        - src: "../files/emby/Movies_options.xml"
          dest: "{{ emby_root }}/root/default/Movies/options.xml"
      notify:
        - Restart Emby
