---

- hosts: all
  vars:
    emby_version: "4.6.4.0"
    emby_download_url: "https://github.com/MediaBrowser/Emby.Releases/releases/download/{{ emby_version }}/emby-server-deb_{{ emby_version }}_amd64.deb"
  tasks:
    - name: Install Emby
      apt:
        deb: "{{ emby_download_url }}"
      # https://github.com/ansible/ansible/issues/45219
      environment:
        PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

    - name: Ensure Emby server is enabled
      systemd:
        name: "emby-server"
        enabled: true
        state: started
      # Skipping check mode since its causes issues :(
      when: not ansible_check_mode
