---

- hosts: all
  tasks:

    - name: "Installing ubuntu-drivers-common"
      package:
        name: "ubuntu-drivers-common"

    - name: "Install drivers"
      shell: "ubuntu-drivers --gpgpu autoinstall"
