---

- hosts: all
  tasks:

    - name: "Installing required packages"
      package:
        name: "{{ item }}"
      with_items:
        - "nvidia-modprobe"
        - "ubuntu-drivers-common"

    - name: "Install drivers"
      shell: "ubuntu-drivers --gpgpu autoinstall"
