---

- hosts: all
  tasks:

    - name: "Installing ubuntu-drivers-common"
      package:
        name: "ubuntu-drivers-common"

    - name: "Install drivers"
      shell: "ubuntu-drivers --gpgpu autoinstall"
      register: gpu_install

    - name: "reboot server"
      shell: sleep 5 && reboot &
      async: 1
      poll: 0
      when: gpu_install is changed

    - name: "wait for server"
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 600
