---

- hosts: all
  handlers:
    - name: Update Grub
      command: update-grub
  tasks:
    # https://unix.stackexchange.com/questions/25133/ubuntu-server-continuously-goes-to-sleep/25151#25151
    - name: "Disable System sleep"
      lineinfile:
        dest: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="acpi=off apm=off"'
        mode: 0644
        backup: true
      notify:
        - Update Grub
