---

- name: "Install and Setup Jellyfin"
  hosts: localhost
  connection: local
  vars:
    jellyfin_root: "/var/lib/jellyfin/root"
    jellyfin_version: "10.9.7+ubu2004"

  handlers:
    - name: Restart Jellyfin
      systemd:
        name: "jellyfin"
        state: restarted
      # Skipping check mode since its causes issues :(
      when: not ansible_check_mode

  tasks:
    - name: Add an Apt signing key for Jellyfin
      apt_key:
        url: https://repo.jellyfin.org/jellyfin_team.gpg.key
        state: present

    - name: Add Jellyfin repository
      apt_repository:
        repo: deb [arch=amd64] https://repo.jellyfin.org/ubuntu focal main
        state: present
        filename: jellyfin

    - name: Get Jellyfin installed version
      shell:
        cmd: dpkg-query -f '${Version}' -W jellyfin
      register: dpkg_query_jellyfin_version
      ignore_errors: true

    - name: Setting jellyfin_installed_version fact
      set_fact:
        jellyfin_installed_version: "{{ dpkg_query_jellyfin_version.stdout | default('') }}"

    - name: Allow jellyfin to be upgraded
      dpkg_selections:
        name: jellyfin
        selection: install
      when:
        - jellyfin_installed_version != jellyfin_version
        - not ansible_check_mode

    - name: Install Jellyfin
      apt:
        name: "jellyfin={{ jellyfin_version }}"
        update_cache: true
        allow_change_held_packages: false
      # https://github.com/ansible/ansible/issues/45219
      environment:
        PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      when:
        - jellyfin_installed_version != jellyfin_version
        - not ansible_check_mode

    - name: Prevent jellyfin from being upgraded
      dpkg_selections:
        name: jellyfin
        selection: hold

    - name: Ensure Jellyfin server is enabled
      systemd:
        name: "jellyfin"
        enabled: true
        state: started
      # Skipping check mode since its causes issues :(
      when: not ansible_check_mode

    - name: Create folders for content
      file:
        state: directory
        path: "{{ jellyfin_root }}"
        owner: "jellyfin"
        group: "jellyfin"

    - name: Copy over system config file
      copy:
        src: "../files/jellyfin/{{ item }}"
        dest: "/etc/jellyfin/{{ item }}"
        owner: "jellyfin"
        group: "jellyfin"
      notify:
        - Restart Jellyfin
      with_items:
        - "system.xml"
        - "encoding.xml"

    - name: Copy over library content configuration files
      synchronize:
        src: "../files/jellyfin/default"
        dest: "{{ jellyfin_root }}"
        delete: true
        recursive: true
        copy_links: true
        checksum: true
        archive: false
      notify:
        - Restart Jellyfin

    - name: fixing permission of files that were copied
      file:
        path: "{{ jellyfin_root }}"
        state: directory
        recurse: true
        mode: 0755
        owner: "jellyfin"
        group: "jellyfin"
      notify:
        - Restart Jellyfin
