---

- name: Dynamic Updates
  hosts: localhost
  connection: local
  ignore_errors: true
  vars:
    config_file: '/root/config.ini'
  tasks:
    - name: Check if config file exists
      stat:
        path: "{{ config_file }}"
      register: config_file_exists

    - name: stop play if config file doesn't exist
      meta: end_play
      when: not config_file_exists.stat.exists

    - name: Get IPv4 address
      uri:
        url: "https://api.ipify.org?format=json"
        method: GET
        return_content: true
        body_format: json
      register: ipv4_result
      until: ipv4_result.status == 200
      retries: 10
      delay: 5

    - name: Update Dynamic DNS
      vars:
        namecheap_host: "{{ lookup('ini', 'host section=namecheap file={{ config_file }}') }}"
        namecheap_password: "{{ lookup('ini', 'password section=namecheap file={{ config_file }}') }}"
        namecheap_domain: "{{ lookup('ini', 'domain section=namecheap file={{ config_file }}') }}"
        ip: "{{ ipv4_result.json.ip }}"
      uri:
        url: "https://dynamicdns.park-your-domain.com/update?host={{ namecheap_host }}&domain={{ namecheap_domain }}&password={{ namecheap_password }}&ip={{ ip }}"
      no_log: true
      when:
        - namecheap_host != ''
        - namecheap_domain != ''
        - namecheap_password != ''
