---

- name: "Ensuring NAS shares are mounted"
  hosts: localhost
  connection: local
  vars:
    mounts:
      - 'Movies'
      - 'TV Shows'
      - 'Backup'
      - 'Download'
      - 'Syncthing'
      - 'Multimedia'
    nas_root: '/mnt/nas'
    # https://rizvir.com/articles/linux-sysadmin-cheats/
    # Tune NFS 3 mounts
    nfs_mount_opts: 'rsize=32768,wsize=32768,nfsvers=3,tcp,async'
  tasks:
    - name: Installed nfs-common
      package:
        name: nfs-common

    - name: Create required folders
      file:
        state: directory
        path: "{{ nas_root }}/{{ item }}"
      with_items: "{{ mounts }}"

    - name: Adding NAS mount points to fstab
      mount:
        src: "nas.{{ do_domain }}:/{{ item }}"
        path: "{{ nas_root }}/{{ item }}"
        fstype: nfs
        state: mounted
        opts: "{{ nfs_mount_opts }}"
      with_items: "{{ mounts }}"
      when:
        - not ansible_check_mode
