---

- name: "netdata Install and setup"
  hosts: localhost
  connection: local
  vars:
    netdata_docker_image: "docker.io/netdata/netdata:v1.47.0"
  tasks:
    - name: create netdata required folders
      file:
        state: directory
        path: "{{ item }}"
        recurse: true
      with_items:
        - "/opt/netdata/etc"
        - "/opt/netdata/lib"
        - "/opt/netdata/cache"

    - name: Deploy netdata
      docker_container:
        name: "netdata"
        hostname: "netdata"
        image: "{{ netdata_docker_image }}"
        env:
          TZ: 'America/Toronto'
        volumes:
          - "/opt/netdata/etc:/etc/netdata"
          - "/opt/netdata/lib:/var/lib/netdata"
          - "/opt/netdata/cache:/var/cache/netdata"
          - "/:/host/root:ro,rslave"
          - "/etc/passwd:/host/etc/passwd:ro"
          - "/etc/group:/host/etc/group:ro"
          - "/etc/localtime:/etc/localtime:ro"
          - "/proc:/host/proc:ro"
          - "/sys:/host/sys:ro"
          - "/etc/os-release:/host/etc/os-release:ro"
          - "/var/log:/host/var/log:ro"
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
        memory: "1G"
        restart_policy: always
        state: started
        pull: false
        container_default_behavior: "no_defaults"
        network_mode: "host"
        capabilities:
          - SYS_PTRACE
          - SYS_ADMIN
        security_opts:
          - apparmor:unconfined
      # added retry to tasks dependant on external services
      register: result
      retries: 5
      delay: 3
      until: result is succeeded
      when: not ansible_check_mode
