---

- name: "Playbook to update packages and reboot machine if required"
  hosts: localhost
  connection: local
  tasks:
    - name: "Only run update out of hours unless forced"
      block:
        - name: "update all packages"
          apt:
            name: "*"
            state: latest

        - name: "check if reboot is required"
          stat:
            path: /var/run/reboot-required
          register: reboot_required

        - name: "Reboot"
          reboot:
            msg: "Reboot triggered by Ansible"
          when: reboot_required.stat.exists
      when: (ansible_date_time.hour | int == 2 and ansible_date_time.minute | int < 10) or
            (force_run_update is defined and force_run_update)
