---

- name: "Playbook to update packages and reboot machine if required"
  hosts: localhost
  connection: local
  tasks:
    - name: "Set facts for time"
      set_fact:
        hour_now: "{{ ansible_date_time.hour | int }}"
        minute_now: "{{ ansible_date_time.minute | int }}"

    - name: "print ansible_date_time"
      debug:
        msg:
          - "{{ hour_now }}"
          - "{{ minute_now }}"

    - name: stop play if its not the right time
      meta: end_play
      when: (hour_now | int != 2 and minute_now | int > 10) or
            (force_run_update is defined and force_run_update == False)

    - name: "update all packages"
      apt:
        name: "*"
        state: latest

    - name: "check if reboot is required"
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: "Reboot"
      shell: sleep 5 && reboot &
      async: 1
      poll: 0
      when: reboot_required.stat.exists
