---

- name: "Pihole Install and setup"
  hosts: localhost
  connection: local
  vars:
    pihole_docker_image: "pihole/pihole:2022.09.4"
    pihole_exporter_docker_image: "ekofr/pihole-exporter:v0.0.11"
    custom_ad_list: |
      https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      https://raw.githubusercontent.com/ahmedsajid/pihole/master/adlist.txt
      https://raw.githubusercontent.com/ahmedsajid/pihole/master/sunburst.txt
      https://raw.githubusercontent.com/ahmedsajid/pihole/master/youtube1.txt
      https://raw.githubusercontent.com/ahmedsajid/pihole/master/youtube2.txt
    service_list:
      - emby
      - syncthing
      - prometheus
      - grafana
      - webui-aria
    unbound_role_version: v2.1.3
  tasks:
    - name: create role folder
      file:
        state: directory
        path: /root/.ansible/roles

    - name: Clone role ahmedsajid.unbound
      git:
        repo: 'https://github.com/ahmedsajid/ansible-role-unbound.git'
        dest: /root/.ansible/roles/ahmedsajid.unbound
        version: "{{ unbound_role_version }}"
      # added retry to tasks dependant on external services
      register: result
      retries: 5
      delay: 3
      until: result is succeeded

    - name: Using unbound role
      include_role:
        name: ahmedsajid.unbound
      vars:
        unbound_interfaces:
          - 127.0.0.1@5353
        unbound_forward_zone_configuration:
          - forward-tls-upstream: "yes"
        unbound_configuration:
          - verbosity: 1
          - do-ip4: "yes"
          - do-ip6: "no"
          - do-udp: "yes"
          - do-tcp: "yes"
          - num-threads: 1
          - pidfile: "/var/run/unbound.pid"
          - logfile: "{{unbound_logfile}}"
          - log-time-ascii: "yes"
          - log-queries: "yes"
          - log-replies: "yes"
          - log-tag-queryreply: "yes"
          - log-local-actions: "yes"
          - log-servfail: "yes"
      when: not ansible_check_mode

    - name: create pihole required folders
      file:
        state: directory
        path: "{{ item }}"
      with_items:
        - "/opt/pihole/etc"
        - "/opt/pihole/dnsmasq.d/"

    - name: Deploy pihole custom adlist
      copy:
        dest: "/opt/pihole/etc/adlists.list"
        content: "{{ custom_ad_list }}"
        mode: 0640

    - name: Deploy custom dns entries
      copy:
        dest: "/opt/pihole/etc/custom.list"
        content: |
          {% for service in service_list %}
          {{ ansible_default_ipv4.address }} {{ service }}.lan
          {% endfor %}
        mode: 0640

    - name: Deploy pihole container
      docker_container:
        name: "pihole"
        hostname: "pihole"
        image: "{{ pihole_docker_image }}"
        network_mode: "host"
        env:
          TZ: 'America/Toronto'
          PIHOLE_DNS_: '127.0.0.1#5353'
          WEBPASSWORD: ''
          INTERFACE: "{{ ansible_default_ipv4.interface }}"
          ServerIP: "{{ ansible_default_ipv4.address }}"
          DNSMASQ_LISTENING: "all"
        capabilities:
          - NET_ADMIN
        restart_policy: always
        state: started
        pull: false
        volumes:
          - '/opt/pihole/etc/:/etc/pihole/'
          - '/opt/pihole/dnsmasq.d/:/etc/dnsmasq.d/'
      # added retry to tasks dependant on external services
      register: result
      retries: 5
      delay: 3
      until: result is succeeded

    - name: Deploy pihole exporter
      docker_container:
        name: "pihole-exporter"
        hostname: "pihole-exporter"
        image: "{{ pihole_exporter_docker_image }}"
        env:
          TZ: 'America/Toronto'
          PIHOLE_HOSTNAME: "{{ ansible_default_ipv4.address }}"
          PIHOLE_PASSWORD: ''
          INTERVAL: '30s'
          PORT: '9617'
        ports:
          - '9617:9617'
        restart_policy: always
        state: started
        pull: false
      # added retry to tasks dependant on external services
      register: result
      retries: 5
      delay: 3
      until: result is succeeded

    - name: Set facts for time
      set_fact:
        minute_now: "{{ ansible_date_time.minute | int }}"

    - name: Print ansible_date_time
      debug:
        msg:
          - "{{ minute_now }}"

    - name: Update pihole gravity
      command: docker exec -t pihole pihole -g
      when: minute_now | int < 10 or
            (force_gravity_update is defined and force_gravity_update)
