---

- name: "Installing and setting up prometheus"
  hosts: localhost
  connection: local
  tasks:
    - name: create role folder
      file:
        state: directory
        path: /root/.ansible/roles

    - name: Clone role cloudalchemy.prometheus
      git:
        repo: 'https://github.com/cloudalchemy/ansible-prometheus.git'
        dest: /root/.ansible/roles/cloudalchemy.prometheus
        version: 4.0.0

    - name: Using cloudalchemy ansible-prometheus role
      include_role:
        name: cloudalchemy.prometheus
      vars:
        prometheus_targets:
          node:
            - targets:
                - localhost:9100
              labels:
                env: next
      when: not ansible_check_mode
