---

- hosts: all
  tasks:
    - name: create role folder
      file:
        state: directory
        path: /root/.ansible/roles
      delegate_to: localhost

    - name: Clone role ahmedsajid.unbound
      git:
        repo: 'https://github.com/ahmedsajid/ansible-role-unbound.git'
        dest: /root/.ansible/roles/ahmedsajid.unbound
        version: v2.1.1

    - name: Using unbound role
      include_role:
        name: ahmedsajid.unbound
      vars:
        unbound_interfaces:
          - 127.0.0.1@5353
        unbound_forward_zone_configuration:
          - forward-tls-upstream: "yes"
      when: not ansible_check_mode
