---

- name: Read ini config file
  import_playbook: "read_config_file.yml"

- name: "Vault Warden"
  hosts: localhost
  connection: local
  vars:
    vaultwarden_docker_image: "vaultwarden/server:1.37.1"
  tasks:
    - name: create vaultwarden required folder
      file:
        state: directory
        path: "{{ item }}"
      with_items:
        - "/opt/vaultwarden"
        - "/mnt/nas/Backup/vaultwarden"

    - name: Deploy vaultwarden container
      docker_container:
        name: "vaultwarden"
        hostname: "vaultwarden"
        image: "{{ vaultwarden_docker_image }}"
        env:
          TZ: 'America/Toronto'
        labels:
          traefik.enable: "true"
          traefik.docker.network: "app_network"
          traefik.http.routers.pass.rule: "Host(`pass.{{ do_domain }}`)"
          traefik.http.routers.pass.entrypoints: "https"
          traefik.http.routers.pass.tls: "true"
          traefik.http.routers.pass.middlewares: "pass-iprestrict"
          traefik.http.middlewares.pass-iprestrict.ipallowlist.sourcerange: "{{ traefik_private_ipallowlist_sourcerange }}"
          traefik.http.middlewares.pass-iprestrict.ipallowlist.rejectstatuscode: "{{ traefik_ip_reject_status_code }}"
          traefik.http.services.pass.loadbalancer.server.port: "80"
        networks:
          - name: "app_network"
        restart_policy: always
        state: started
        pull: false
        memory: '1G'
        network_mode: "bridge"
        container_default_behavior: "compatibility"
        comparisons:
          labels: strict
        volumes:
          - '/opt/vaultwarden:/data/'
      # added retry to tasks dependant on external services
      register: result
      retries: 5
      delay: 3
      until: result is succeeded
      when:
        - not ansible_check_mode

    - name: Set today's vaultwarden backup path
      set_fact:
        vaultwarden_backup_file: "/mnt/nas/Backup/vaultwarden/vaultwarden-backup-{{ ansible_date_time.date }}.tgz"

    - name: Check whether today's vaultwarden backup already exists
      stat:
        path: "{{ vaultwarden_backup_file }}"
      register: vaultwarden_todays_backup

    - name: Run daily vaultwarden backup if missing
      block:
        - name: Create archive
          archive:
            path: /opt/vaultwarden
            dest: "{{ vaultwarden_backup_file }}"

        - name: Find older backups
          find:
            paths: /mnt/nas/Backup/vaultwarden/
            age: 5d
            recurse: true
          register: vaultwarden_old_backups

        - name: Remove older backups
          file:
            path: "{{ item.path }}"
            state: absent
          with_items: "{{ vaultwarden_old_backups.files }}"
      when: (not vaultwarden_todays_backup.stat.exists) or
            (force_vaultwarden_backup is defined and force_vaultwarden_backup | bool)
