---

- name: "Webui-Aria2 setup"
  hosts: localhost
  connection: local
  tasks:
    - name: Deploy webui-aria2 container
      docker_container:
        name: "webui-aria2"
        hostname: "webui-aria2"
        image: "ahmedsajid/webui-aria2"
        env:
          TZ: 'America/Toronto'
        ports:
          - "6800:6800"
          - "8080:8080"
        restart_policy: always
        state: started
        pull: false
        volumes:
          - '/mnt/nas/Download:/data'
