---

- name: "Webui-Aria2 setup"
  hosts: localhost
  connection: local
  tasks:
    - name: Deploy webui-aria2 container
      docker_container:
        name: "webui-aria2"
        hostname: "webui-aria2"
        image: "ahmedsajid/webui-aria2"
        env:
          TZ: 'America/Toronto'
        # ports:
        #   - "6800:6800"
        networks:
          - name: "app_network"
        restart_policy: always
        state: started
        pull: false
        volumes:
          - '/mnt/nas/Download:/data'
        network_mode: "default"
        container_default_behavior: "compatibility"
        labels:
          traefik.enable: "true"
          traefik.docker.network: "app_network"
          traefik.http.routers.webui-aria2.rule: "Host(`webui-aria2.{{ do_domain }}`)"
          traefik.http.routers.webui-aria2.entrypoints: "https"
          traefik.http.routers.webui-aria2.tls: "true"
          traefik.http.routers.webui-aria2.tls.certresolver: "le"
          traefik.http.services.webui-aria2.loadbalancer.server.port: "8080"
      # added retry to tasks dependant on external services
      register: result
      retries: 5
      delay: 3
      until: result is succeeded
      when: not ansible_check_mode
