---

name: auto-merge

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:
  apply-auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Run auto-merge
        if: ${{ github.actor == github.repository_owner }}
        run: |
          echo ${PR}
          if [ "${ACTOR}" = "${OWNER}" ]; then
            gh pr merge --auto -s
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.number }}
