---
name: auto-merge

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:
  apply-auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: auto-merge
        uses: actions/github-script@v4
        with:
          script: |

            console.log(context.repo.owner)
            console.log(context.actor)
            console.log(github.issues)

            // if (context.actor === context.repo.owner) {
            // }
