---

name: auto-merge

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:
  apply-auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Run auto-merge
        if: ${{ github.actor == github.repository_owner }}
        run: gh pr merge ${PR} --auto -s -d -R ${GITHUB_REPO}
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
          PR: ${{ github.event.number }}
