---

name: checks

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:


env:
  PRE_COMMIT_VERSION: "2.16.0"
  ANSIBLE_VERSION: "6.7.0"

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checking out repo
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
      - name: Install pre-commit $PRE_COMMIT_VERSION
        run: pip install pre-commit==$PRE_COMMIT_VERSION
      - name: Run pre-commit
        run: pre-commit run --all-files
  # Testing ansible-pull that is ran via cronjob
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checking out repo
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
      - name: Install python3-docker
        run: sudo apt-get -y install python3-docker
      - name: Install ansible $ANSIBLE_VERSION
        run: pip install ansible==$ANSIBLE_VERSION
      - name: Run Ansible test
        run: ansible-playbook --inventory '127.0.0.1,' --connection local --become --check local.yml -e digitalocean_host='*' -e digitalocean_domain='example.com' -e digitalocean_token='randomtoken' -e config_deploy=true
        working-directory: ./ansible
