---

name: checks

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out repo
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
    - name: Run pre-commit checks
      uses: pre-commit/action@v2.0.3
  # Testing first deploy ansible pull playbook
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out repo
      uses: actions/checkout@v2
    - name: Run Ansible test
      uses: dawidd6/action-ansible-playbook@v2
      with:
        # Required, playbook filepath
        playbook: ansible_pull.yml
        # Optional, directory where playbooks live
        directory: ./ansible
        # Optional, literal inventory file contents
        inventory: |
          [all]
          127.0.0.1 ansible_connection=local
        options: |
          --become
          --check
  # Testing ansible-pull that is ran via cronjob
  test-pull:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out repo
      uses: actions/checkout@v2
    - name: Install python3-docker
      run: sudo apt-get -y install python3-docker
    - name: Generating test config.ini file
      run: |
        cat << EOF > /tmp/config.ini
        [healthchecks.io]
        uuid=somerandomuuid

        [noip]
        hostname=myhostname
        username=myusername
        password=mypassword
        EOF
    - name: Run Ansible test
      uses: dawidd6/action-ansible-playbook@v2
      with:
        # Required, playbook filepath
        playbook: local.yml
        # Optional, directory where playbooks live
        directory: ./ansible
        # Optional, literal inventory file contents
        inventory: |
          [all]
          127.0.0.1 ansible_connection=local
        options: |
          --become
          --check
          --extra-vars config_file=/tmp/config.ini
