---

name: pre-commit-autoupdate

on:
  # schedule:
  #   - cron: '0 0 * * 0'
  workflow_dispatch:

env:
  PRE_COMMIT_VERSION: "2.16.0"

jobs:
  autoupdate:
    runs-on: ubuntu-20.04
    steps:
      - name: Checking out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v5
      - name: Install pre-commit $PRE_COMMIT_VERSION
        run: pip install pre-commit==$PRE_COMMIT_VERSION
      - name: Run pre-commit autoupdate
        run: pre-commit autoupdate
      - name: Create PR if required
        run: |
          # If there are changes, only then continue
          if [[ $(git status --porcelain | wc -l) -gt 0 ]]; then
              DATENOW=$(date '+%s')
              # Adding author info
              git config user.name github-actions
              git config user.email github-actions@github.com
              git checkout -b pre-commit-autoupdate-${DATENOW}
              git add -A
              git commit -m "chore: pre-commit autoupdate"
              git push -u origin HEAD
              gh pr create --fill
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
