---

name: testing

on:
  pull_request:
    paths: 'ansible/**'
  push:
    branches: [main]
    paths: 'ansible/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out repo
      uses: actions/checkout@v2
    - name: Install python3-docker
      run: sudo apt-get -y install python3-docker
    - name: Run Ansible test
      uses: dawidd6/action-ansible-playbook@v2
      with:
        # Required, playbook filepath
        playbook: local.yml
        # Optional, directory where playbooks live
        directory: ./ansible
        # Optional, literal inventory file contents
        inventory: |
          [all]
          127.0.0.1 ansible_connection=local
        options: |
          --become
          --check
